const LS_KEYS = {
  USER: "currentUser",
  AUTH_TOKEN: "token",
  SIGNUP_EMAIL: "signupEmail",
};

const UserFlowStatus = {
  LOGGED_OUT: "LOGGED_OUT",
  LOGGED_IN: "LOGGED_IN",
  EMAIL_UNVERIFIED: "EMAIL_UNVERIFIED",
  PROFILE_INCOMPLETE: "PROFILE_INCOMPLETE",
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  COMPLETE: "COMPLETE",
};

const ALLOWED_FILE_TYPES = ["image/jpeg", "image/png", "image/webp"];
const MAX_FILE_SIZE = 2 * 1024 * 1024; // 2MB

const CATEGORIES = [
  "Pain Relief",
  "Respiratory",
  "Digestive",
  "Immune Support",
  "Sleep Aid",
  "Skin Care",
];

const REMEDY_TYPES = {
  PHARMACEUTICAL: "pharmaceutical",
  ALTERNATIVE: "alternative",
  COMMUNITY: "community",
};

const TABS = {
  GENERAL: "general",
  INGREDIENTS: "ingredients",
};

const AilmentCategories = [
  "Digestive Health",
  "Mental Health",
  "Respiratory Health",
  "Skin & Dermatology",
  "Cardiovascular Health",
  "Women's Health",
  "Men's Health",
  "Immune System",
  "Muscle & Joint",
  "Sleep & Energy",
  "Hair & Scalp",
  "Allergies & Sensitivities",
  "Urinary & Kidney",
  "Endocrine & Hormones",
  "Oral & Dental",
  "Liver & Detox",
  "Eye & Vision",
  "Ear, Nose & Throat",
  "Neurological",
  "General Wellness",
  "Neurological Health",
  "Skin Health",
  "Immune Health",
  "Reproductive Health",
  "Oral Health",
];


const AilmentInitialState = {
  name: "",
  description: "",
  category: "",
  slug: "",
  symptoms: [],
  causesAndRisks: [],
  preventionTips: [],
  severity: "",
  isCommon: false,
  isContagious: false,
  requiresMedicalAttention: false,
};

const AilmentSeverityOptions = ["mild", "moderate", "severe"];


const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic (Czechia)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];


export {
  AilmentInitialState,
  AilmentSeverityOptions,
  COUNTRIES,
  TABS,
  MAX_FILE_SIZE,
  LS_KEYS,
  UserFlowStatus,
  ALLOWED_FILE_TYPES,
  CATEGORIES,
  REMEDY_TYPES,
  AilmentCategories,
};
